---
apiVersion: snapshot.storage.k8s.io/v1
kind: VolumeSnapshotClass
metadata:
  name: csi-azuredisk-vsc
driver: disk.csi.azure.com
deletionPolicy: Delete
parameters:
  incremental: "true"  # available values: "true", "false" ("true" by default for Azure Public Cloud, and "false" by default for Azure Stack Cloud)
---
apiVersion: snapshot.storage.k8s.io/v1
kind: VolumeSnapshotContent
metadata:
  name: snapshotcontent-tg-data-tigergraph-0
spec:
  deletionPolicy: "Delete"
  driver: "disk.csi.azure.com"
  volumeSnapshotClassName: "csi-azuredisk-vsc"
  source:
    snapshotHandle: /subscriptions/ff13286c-6387-46c7-a1b2-2dda443886ed/resourceGroups/MC_tgsr_tgsr001_westus3/providers/Microsoft.Compute/snapshots/snapshot-0
  volumeSnapshotRef:
    apiVersion: snapshot.storage.k8s.io/v1
    kind: VolumeSnapshot
    name: snapshot-tg-data-tigergraph-0
    namespace: default
---
apiVersion: snapshot.storage.k8s.io/v1
kind: VolumeSnapshot
metadata:
  name: snapshot-tg-data-tigergraph-0
  namespace: default
spec:
  volumeSnapshotClassName: "csi-azuredisk-vsc"
  source:
    volumeSnapshotContentName: snapshotcontent-tg-data-tigergraph-0
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: tigergraph
  name: tg-data-tigergraph-0
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: managed-premium
  resources:
    requests:
      storage: 250Gi
  dataSource:
    name: snapshot-tg-data-tigergraph-0
    kind: VolumeSnapshot
    apiGroup: snapshot.storage.k8s.io
---
apiVersion: snapshot.storage.k8s.io/v1
kind: VolumeSnapshotContent
metadata:
  name: snapshotcontent-tg-data-tigergraph-1
spec:
  deletionPolicy: "Delete"
  driver: "disk.csi.azure.com"
  volumeSnapshotClassName: "csi-azuredisk-vsc"
  source:
    snapshotHandle: /subscriptions/ff13286c-6387-46c7-a1b2-2dda443886ed/resourceGroups/MC_tgsr_tgsr001_westus3/providers/Microsoft.Compute/snapshots/snapshot-1
  volumeSnapshotRef:
    apiVersion: snapshot.storage.k8s.io/v1
    kind: VolumeSnapshot
    name: snapshot-tg-data-tigergraph-1
    namespace: default
---
apiVersion: snapshot.storage.k8s.io/v1
kind: VolumeSnapshot
metadata:
  name: snapshot-tg-data-tigergraph-1
  namespace: default
spec:
  volumeSnapshotClassName: "csi-azuredisk-vsc"
  source:
    volumeSnapshotContentName: snapshotcontent-tg-data-tigergraph-1
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: tigergraph
  name: tg-data-tigergraph-1
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: managed-premium
  resources:
    requests:
      storage: 250Gi
  dataSource:
    name: snapshot-tg-data-tigergraph-1
    kind: VolumeSnapshot
    apiGroup: snapshot.storage.k8s.io
---
apiVersion: snapshot.storage.k8s.io/v1
kind: VolumeSnapshotContent
metadata:
  name: snapshotcontent-tg-data-tigergraph-2
spec:
  deletionPolicy: "Delete"
  driver: "disk.csi.azure.com"
  volumeSnapshotClassName: "csi-azuredisk-vsc"
  source:
    snapshotHandle: /subscriptions/ff13286c-6387-46c7-a1b2-2dda443886ed/resourceGroups/MC_tgsr_tgsr001_westus3/providers/Microsoft.Compute/snapshots/snapshot-2
  volumeSnapshotRef:
    apiVersion: snapshot.storage.k8s.io/v1
    kind: VolumeSnapshot
    name: snapshot-tg-data-tigergraph-2
    namespace: default
---
apiVersion: snapshot.storage.k8s.io/v1
kind: VolumeSnapshot
metadata:
  name: snapshot-tg-data-tigergraph-2
  namespace: default
spec:
  volumeSnapshotClassName: "csi-azuredisk-vsc"
  source:
    volumeSnapshotContentName: snapshotcontent-tg-data-tigergraph-2
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: tigergraph
  name: tg-data-tigergraph-2
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: managed-premium
  resources:
    requests:
      storage: 250Gi
  dataSource:
    name: snapshot-tg-data-tigergraph-2
    kind: VolumeSnapshot
    apiGroup: snapshot.storage.k8s.io
---
apiVersion: snapshot.storage.k8s.io/v1
kind: VolumeSnapshotContent
metadata:
  name: snapshotcontent-tg-data-tigergraph-3
spec:
  deletionPolicy: "Delete"
  driver: "disk.csi.azure.com"
  volumeSnapshotClassName: "csi-azuredisk-vsc"
  source:
    snapshotHandle: /subscriptions/ff13286c-6387-46c7-a1b2-2dda443886ed/resourceGroups/MC_tgsr_tgsr001_westus3/providers/Microsoft.Compute/snapshots/snapshot-3
  volumeSnapshotRef:
    apiVersion: snapshot.storage.k8s.io/v1
    kind: VolumeSnapshot
    name: snapshot-tg-data-tigergraph-3
    namespace: default
---
apiVersion: snapshot.storage.k8s.io/v1
kind: VolumeSnapshot
metadata:
  name: snapshot-tg-data-tigergraph-3
  namespace: default
spec:
  volumeSnapshotClassName: "csi-azuredisk-vsc"
  source:
    volumeSnapshotContentName: snapshotcontent-tg-data-tigergraph-3
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: tigergraph
  name: tg-data-tigergraph-3
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: managed-premium
  resources:
    requests:
      storage: 250Gi
  dataSource:
    name: snapshot-tg-data-tigergraph-3
    kind: VolumeSnapshot
    apiGroup: snapshot.storage.k8s.io
